# Generated by Django 5.0.3 on 2024-05-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='example_input',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='example_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
    ]
